# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 21:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(default=datetime.datetime(2017, 7, 31, 21, 19, 58, 688325, tzinfo=utc), unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Souvenir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=150)),
                ('journee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal_de_bord.Journee')),
            ],
        ),
    ]
