# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_de_bord', '0002_delete_helloworld'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journee',
            name='lever',
            field=models.TimeField(blank=True, default='0:0', null=True),
        ),
    ]
