# Generated by Django 2.0.5 on 2018-05-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_de_bord', '0003_auto_20171101_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='journee',
            name='dure',
            field=models.TimeField(blank=True, default='0:0', null=True),
        ),
    ]
