# Generated by Django 2.0.5 on 2018-05-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_de_bord', '0004_journee_dure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journee',
            name='dure',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journee',
            name='lever',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
