# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 22:49
from __future__ import unicode_literals

import arrow.api
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_de_bord', '0005_auto_20170801_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journee',
            name='jour',
            field=models.DateField(default=arrow.api.utcnow, unique=True),
        ),
    ]
