# Generated by Django 2.0.5 on 2018-05-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_de_bord', '0006_remove_journee_dure'),
    ]

    operations = [
        migrations.AddField(
            model_name='journee',
            name='dure',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
