# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-07 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_de_bord', '0008_auto_20180807_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='journee',
            name='dure_temp',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journee',
            name='dure',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
