# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_de_bord', '0009_auto_20170803_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journee',
            name='jour',
            field=models.DateField(unique=True),
        ),
    ]
