# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_de_bord', '0010_auto_20170803_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='souvenir',
            name='texte',
            field=models.TextField(),
        ),
    ]
