# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-07 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal_de_bord', '0010_remove_journee_dure'),
    ]

    operations = [
        migrations.AddField(
            model_name='journee',
            name='dure',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
