# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-07 06:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal_de_bord', '0011_journee_dure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journee',
            name='dure_temp',
        ),
    ]
